name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [latest, 14, 16]
    env:
      repo: "govpf/node-dev"
    steps:

    - name: Checkout
      uses: actions/checkout@v4.0.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.7.1

    - name: Build
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./${{ matrix.versions }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:${{ matrix.versions }}
